name       : perl-glib
version    : 1.325
release    : 2
source     :
    - https://netcologne.dl.sourceforge.net/project/gtk2-perl/Glib/1.325/Glib-1.325.tar.gz : 04b3ff35a21d06509f2eb5769d161217cc3c92dd60204fc778cf089eb80b7b15
license    : LGPL-2.1
component  : programming.python
summary    : Perl wrappers for glib 2.x, including GObject
description: |
    Perl wrappers for glib 2.x, including GObject
builddeps  :
    - perl-extutils-depends
    - perl-extutils-pkgconfig
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
