name       : perl-glib
version    : '1.3293'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/X/XA/XAOC/Glib-1.3293.tar.gz : 7316a0c1e7cc5cb3db7211214f45d7bdc2354365a680ac4bd3ac8bf06d1cb500
homepage   : http://gtk2-perl.sourceforge.net/
license    : LGPL-2.1-or-later
component  : programming.perl
summary    : Perl wrappers for glib 2.x, including GObject
description: |
    This wrapper attempts to provide a perlish interface while remaining as true as possible to the underlying C API, so that any reference materials you can find on using GLib may still apply to using the libraries from perl. This module also provides facilities for creating wrappers for other GObject-based libraries.
builddeps  :
    - perl-extutils-depends
    - perl-extutils-pkgconfig
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
