name       : perl-glib
version    : 1.326
release    : 3
source     :
    - https://downloads.sourceforge.net/project/gtk2-perl/Glib/1.326/Glib-1.326.tar.gz : 020d0308220cb6e03a086bd45d33dd8fe03b265c502bfc2b4e58f2dbe64c365f
license    : LGPL-2.1
component  : programming.perl
summary    : Perl wrappers for glib 2.x, including GObject
description: |
    Perl wrappers for glib 2.x, including GObject
builddeps  :
    - perl-extutils-depends
    - perl-extutils-pkgconfig
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
